name: CI devops 2021 EPF

on:
  push:
    branches: "master"
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.3


      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: "11"
          cache: "maven"
          
      - name: Build and test with Maven
        run: mvn package --file ./simple-api
