name: CI devops 2021 EPF

on:
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.3

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: "11"
          cache: "maven"
          
      - name: Build and test with Maven
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify sonar:sonar -Dsonar.projectKey=devops-epf -Dsonar.organization=devops-epf-10 -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{secrets.SONAR_TOKEN }} --file ./simple-api/pom.xml
        

  build-and-push-docker-image:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image and push backend
        uses: docker/build-push-action@v2
        with:
          context: ./simple-api
          tags: ${{secrets.DOCKERHUB_USERNAME}}/takima_devops_master:simple-api
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Build image and push database
        uses: docker/build-push-action@v2
        with:
          context: ./database
          tags: ${{secrets.DOCKERHUB_USERNAME}}/takima_devops_master:database
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Build image and push httpd      
        uses: docker/build-push-action@v2
        with:
          context: ./httpd
          tags: ${{secrets.DOCKERHUB_USERNAME}}/takima_devops_master:httpd
          push: ${{ github.ref == 'refs/heads/main' }}
