name: CI devops 2021 EPF

on:
  push:
    branches: [ master ]
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  jobs-name:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.3

      - name: Set up JDK 11
      - uses: actions/setup-java@v2
      # Runs a set of commands using the runners shell
      - name: Build and test with Maven
      - uses: mvn clean verify --file /simple-api
